permalink: pretty
title: 'Refatore'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"

footer:
  copyright_text: 'Programação para escolas públicas | Refatore 2021'

seo:
  meta_og_title: "Programação para escolas públicas"
  meta_og_type: "website"
  meta_og_url: "https://refatore.com"
  meta_og_image: "https://re-fatore.github.io/website/images/logo/logo-mobile.png"
  meta_og_description: "Simples, divertida e tecnológica: Conheça a Refatore."

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md